version: "3.8"

services:
  mongo:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
    environment:
      PORT: 3333
      DATABASE_URL: mongodb://mongo:27017/your-database-name
      JWT_SECRET: ThisIsSomeDeepSecret
    depends_on:
      - mongo
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      VITE_BACKEND_URL: "http://localhost:3333/api/v1"
    volumes:
      - ./frontend:/app

volumes:
  mongo-data:
